vich_uploader:
    db_driver: orm
    metadata :
     type : attribute

    mappings:
        club_logo:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
